[platformio]
boards_dir = boards

[env:esp32c5]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-c5-m4-evk
framework = arduino
board_build.mcu = esp32c5
board_build.variant = esp32c5
; Quan trọng: Ép kiểu target cho compiler
build_flags = 
    -DCONFIG_IDF_TARGET_ESP32C5=1
    -DARDUINO_USB_CDC_ON_BOOT=1
